name: rawcuts_pvt_ltd
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1

  provider: ^5.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  easy_loader: ^1.0.3
  badges: ^2.0.1
  font_awesome_flutter: ^9.1.0
  flutter_spinkit: ^5.1.0
  firebase_auth: ^3.1.4
  firebase_core: ^1.4.0
  cloud_firestore: ^2.5.0
  firebase_storage: ^10.0.2
  dots_indicator: ^2.0.0
  geolocator: ^7.4.0
  google_maps_flutter: ^2.0.6
  geocoder:
  animated_splash_screen: ^1.1.0
  url_launcher: ^6.0.12
  flutter_phone_direct_caller: ^2.0.0
  uuid: ^3.0.4
  persistent_bottom_nav_bar: ^4.0.2
  flutter_zoom_drawer: ^2.1.1
  shared_preferences: ^2.0.7
  animated_check: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/rodfat-two-demo.ttf
